source/nijigenerate/viewport/common/mesheditor/tools/select.d

https://github.com/Inochi2D/inochi-creator/issues/188
When in deformation mode, if the mesh has been rotated along the x and y axes, the cursor position may not align as expected. Here is a temporary fix to make the cursor visible.

[Temporary Fix] Draw the cursor on mesh plane when deform

---

.github/workflows/nightly.yml

This PR adds the ability to generate debug artifacts for the bundled flatpak nightly release.
If both versions are installed, you can use [flatpak debugging capabilities](https://docs.flatpak.org/en/latest/debugging.html).
For example, if you run 
```sh
flatpak run --devel --command="gdb" io.github.nijigenerate.nijiexpose --ex "r" nijiexpose
```
you'll have the symbols available to debug the app through gdb.

Generate debug artifacts for flatpak nightly release

---

BUILD.md
README.md

Hi, I have added a build guide, which has been tested on x86_64 Docker containers running both Ubuntu 22.04 and Arch Linux. This should help those interested in compiling or contributing to the project.

Added build quick start documentation for new contributors and users

---

BUILD.md

also, added `--recurse-submodules` to the i2d-imgui repo

Add Fedora requirements to BUILD.md

---

source/nijigenerate/panels/viewport.d
source/nijigenerate/viewport/package.d

Fixed the issue where the "Mirror View" and "Flip Pairings" labels were the same, causing "Flip Pairings" to not work.
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-windows-with-the-same-label
Use standard D features instead of memcpy

Fixed Mirror View and Flip Pairings igButton Label Collision and Use Standard D Features

---

source/nijigenerate/io/kra.d
source/nijigenerate/io/psd.d
source/nijigenerate/package.d

Fixed bug reported by yussuna
Reproduced by Grillo
1. import psd
2. open animation panel
3. create new animation
Initialize animation after psd/kra imported

Fixed animation create crash when import PSD or KRA

---

source/nijigenerate/viewport/model/package.d

This PR introduces a new sorting method based on object size and sets it as the default sorting mode in the viewport right-click menu.
- **Default Behavior**: Updated the default sorting mode to `SizeSort` to enhance the selection of smaller, detailed objects
- **Heuristic**: Prioritizing smaller objects makes it easier for users to select intricate items they are pointing at, while larger objects can still be selected by clicking elsewhere if needed.
- **Comparison**: 
- Z sorting may produce unreliable results when objects contain a lot of alpha pixels.
- Other solutions that use pixel or mesh-based intersection calculations can reduce performance and increase complexity. The `SizeSort` approach avoids these issues, offering a simpler alternative.
- Combining `SizeSort` and `ZSort` to …

Add SizeSort for Viewport Right Click Menu Sorting

---

source/nijigenerate/widgets/shadow.d

When use ASAN to compile the release version, starting nijigenerate will cause ASAN to detect a memcpy-param-overlap. To ensure safety, memcpy should be replaced with memmove.
This may cause security issues please see
[NVD - CVE-2018-7577](https://nvd.nist.gov/vuln/detail/CVE-2018-7577)
[NVD - CVE-2020-21844](https://nvd.nist.gov/vuln/detail/CVE-2020-21844)
[NVD - CVE-2018-13869](https://nvd.nist.gov/vuln/detail/CVE-2018-13869)
OS: `macos`
commit: `b728b5a2a74f22ecb87cb3c587d7465e054e96ad`
```d
diff --git a/dub.sdl b/dub.sdl
index fa8a6a8..cb3d775 100644
--- a/dub.sdl
+++ b/dub.sdl
@@ -42,7 +42,7 @@ configuration "osx-full" {
targetType "executable"
targetPath "out/nijigenerate.app/Contents/MacOS"
subConfiguration "i2d-imgui" "dynamic_dynamicCRT"
-       dflags …
```

Use `memmove` to prevent ASAN memcpy-param-overlap in release build

---

source/nijigenerate/package.d
source/nijigenerate/windows/welcome.d

Currently, the file history will not be updated after the file is deleted. Users may crash when opening files that do not exist. The patch adds a check.
```
std.file.FileException@std/file.d(372): /Users/user/notexistfile.inx: No such file or directory
----------------
??:? object.Throwable.TraceInfo core.runtime.defaultTraceHandler(void*) [0xxxxxxxxxx]
/Users/user/nijilive/source/nijilive/fmt/package.d:36 nijigenerate.ext.ExPuppet nijilive.fmt.inLoadPuppet!(nijigenerate.ext.ExPuppet).inLoadPuppet(immutable(char)[]) [0xxxxxxxxxx]
/Users/user/nijigenerate/source/nijigenerate/package.d:239 void nijigenerate.incOpenProject!(true).incOpenProject(immutable(char)[], immutable(char)[]) [0xxxxxxxxxx]
/Users/user/nijigenerate/source/nijigenerate/package.d:220 void …
```

Avoid crashes when opening files that do not exist

---

CONTRIBUTORS.md

Upstream contributors are also copyright holders, so it's important to leave them in the credits to comply with the license ^^

Restore I2D contributor list in Contributors.md file.

---

source/nijigenerate/io/package.d
source/nijigenerate/package.d

inochi-creator issue
https://github.com/Inochi2D/inochi-creator/issues/392
https://github.com/Inochi2D/inochi-creator/issues/378
Reproduce the crash
1. open inx
2. save as new inx
3. export png or video
4. waiting autosave

Duplicate Dialog return value avoids mistakes reuse reference

---

source/nijigenerate/core/package.d
source/nijigenerate/widgets/modal/package.d

upstream PR: https://github.com/Inochi2D/inochi-creator/pull/396
* Separate rendering of popups in `incBeginLoopNoEv()`
https://github.com/ocornut/imgui/issues/2398
This commit separates the rendering of popups in the `incBeginLoopNoEv()` function to prevent freezing caused by attempting to render multiple popups simultaneously.

fix: Freezing issue with nagscreen and popups

---

source/nijigenerate/package.d
source/nijigenerate/utils/crashdump.d

upstream PR: https://github.com/Inochi2D/inochi-creator/pull/424
upstream PR: https://github.com/Inochi2D/inochi-creator/pull/425
In any case, we should not crash at the user end
This commit reverts the previous FileException only error handling And add runtime error dump to let users know that they should report to developers

Restore Catch Exception Logic

---

source/nijigenerate/package.d
source/nijigenerate/utils/crashdump.d

upstream pr: https://github.com/Inochi2D/inochi-creator/pull/428
Currently writing crash dump, if the path does not exist will cause a crash.
so writing crash dump should in try catch block and handle XDG_STATE_HOME

[BUG] Avoid crashes caused by non-existent crashdump path

---

source/app.d
source/nijigenerate/panels/resource.d
source/nijigenerate/widgets/output.d

Resource panel can change layout of parameters in several ways. This patch stores the current layout status into .inx file.
1) layout of next children.
if any Node is double clicked, sibling node is shown in horizontal direction. this mode can be toggled. So when double clicking again, position is restored to vertical direction.
2) folding status.
if arrows shown in left side is clicked, children are folded and hidden. this can be also toggled.

Resource panel remembers layout status in .inx file.

---

source/nijigenerate/actions/node.d
source/nijigenerate/panels/nodes.d

"Convert to" sometimes failed to alter Node with other types.
This is caused because of inappropriate handling of "inPlace" parameter in copyFrom method in Node object.
Now, "inPlace" parameter is changed to "clone" parameter, and stop to alter original node automatically.
When "clone" parameter is set, "uuid" becomes same as original Node.
With this patch, stability of "Convert to" command improved.

Bug fix: "Convert to" doesn't work correctly.

---

source/nijigenerate/widgets/output.d

igTreeNodeEx return false in certain cases even if user don't specify to fold it.
Existing code detect that event, and set internal status flags.
This patch detect such a condition and ignore even if detecting return value of igTreeNodeEx is false.

Bug fix: Nodes are folded unintentionally in certain conditions.

---

source/nijigenerate/core/cv/contours.d
source/nijigenerate/core/math/path.d
source/nijigenerate/core/math/skeletonize.d
source/nijigenerate/viewport/vertex/package.d
source/nijigenerate/windows/automeshbatch.d

Time consuming task like automesh should be cancelled if user specify to cancel.
This patch introduces fiber for automesh and related time-consuming task, so if user specify to cancel, it discards the task, and returns.

Automesh: Using Fiber to enable cancellation of the task easily.

---

source/app.d
source/nijigenerate/commands/puppet/tool.d
source/nijigenerate/core/window.d
source/nijigenerate/widgets/mainmenu.d

EditMode cannot set correctly from command line, due to the delay of the change in active tab.
In original implementation, when user switches the edit mode by shortcut, edit mode was changed back to original mode, since tab status in main menu is not updated, and reset the mode to previous one.
This patch fixes that bug.
In addition to that, this patch tries to enable screensaver, which was disabled even in editor.

Commands: fixed bug in "mode setting" command and related UI to work correctly.

---

source/nijigenerate/commands/base.d
source/nijigenerate/commands/inspector/apply_node.d
source/nijigenerate/commands/puppet/file.d
source/nijigenerate/windows/settings.d

This PR introduces a `shortcutRunnable()` flag to the Command API and wires the shortcut editor UI to hide commands that should not be directly invoked via shortcuts.
Changes:
- Add `Command.shortcutRunnable()` (default true via `ExCommand`).
- Mark direct file operations as not shortcut-bindable:
- `OpenFileCommand`, `SaveFileCommand` return `false`.
- Filter the Settings → Shortcuts table to omit non-runnable commands.
- Mark Inspector Apply* commands as not shortcut-bindable (value-taking), while Toggle* remain allowed.
Rationale:
- Certain actions (e.g., Save/Load/Import/Merge direct execution, Inspector Apply with explicit values) should go through dialogs or context UI rather than be bound to raw shortcuts.
Build:
- Verified with `dub build -c linux-full`.

feat(commands): hide non-runnable commands from shortcut editor

---

source/nijigenerate/commands/package.d
source/nijigenerate/commands/parameter/group.d
source/nijigenerate/commands/parameter/prop.d
source/nijigenerate/commands/puppet/file.d
source/nijigenerate/windows/parameditor.d

Summary:
- Add ParamProp commands and wire into AllCommandMaps.
- Register defaults for FileCommand Open/Save; align group color schema to float[3].
- ParamEditorWindow: save via commands; axis edit uses display order and keeps binding values by nearest remap.
Commits included:
- 88ccc12 feat(commands): add parameter property commands
- 53023ae fix(commands): register defaults for ExCommand with params and align group color schema
- 0b03357 parameditor/commands: preserve binding data across axis edits

feat(commands,parameditor): add parameter property commands and preserve bindings across axis edits

---

source/nijigenerate/windows/settings.d

This PR improves the **Shortcuts** pane in the settings window by:
- Correcting a typo in the pane name (`Shotcuts` → `Shortcuts`) across the enum, UI selection, and rendering function.
- Adding **filtering functionality** for commands with shortcuts, allowing users to search commands by name.
- Updating the command table to only render commands that match the filter, improving usability in large command sets.
1. Shortcuts pane now displays correctly as `Shortcuts` instead of `Shotcuts`.
2. Filtering example: typing a keyword in the filter input shows only matching commands, making it easier to find specific shortcuts.
- A new `shortcutFilterBuffer` is used to capture user input, and `shortcutFilter` stores the current filter string.
- In `renderCommandTable`, we first build a list of …

Shortcuts Pane Filter

---

source/nijigenerate/commands/viewport/palette.d

This PR improves the **Command Palette** in the viewport by:
- Implementing `deriveEnglishToken` to make commands searchable via their type name (e.g. typing `open` finds `OpenFileCommand` → `[檔案] 開啟`).
-  Using English input is reasonable because ImGui has limited support for CJK input.
- Adding group/category matching so commands can also be found by their parent group name (e.g. searching `檔案` or `File` lists all `nijigenerate.commands.puppet.file.commands`).
- Improving the list height calculation to prevent underflow by ensuring at least 4 elements are considered.
1. Searching in English (`open`) successfully finds i18n-translated commands (UI shows: `[檔案] 開啟`).
2. Searching by group name (`檔案` or `File`) returns all commands in the `File` group …

Command Palette Enhancements

---

source/nijigenerate/viewport/common/mesheditor/tools/connect.d
source/nijigenerate/viewport/common/mesheditor/tools/grid.d
source/nijigenerate/viewport/common/mesheditor/tools/point.d

fix(mesh-editor): make ConnectTool type-safe to prevent BezierDeform segfault
- Updated ToolInfoImpl to check that all targets are Drawable before enabling the tool.
- `canUse` and `viewportTools` now return false for non-Drawable or deformOnly targets.
- Prevents segmentation faults when BezierDeform nodes are present in the selection.
fix(mesh-editor): restrict GridTool and PointTool to Drawable nodes only
- Updated GridTool `viewportTools` and `canUse` to check for Drawable nodes explicitly.
- Prevents crashes when tool is activated on non-Drawable targets.
- hot fix PointTool so vertex auto-connect logic only runs when `implDrawable` is valid.

fix(mesh-editor): type-safe prevent BezierDeform segfault

---

dub.sdl

On macOS, nightly builds fail to compile because `/usr/local/opt/openssl@1.1` only contains x86 or arm libraries, that affected by the compilation environment, and Homebrew has deprecated `openssl@1.1`. The recommended approach is to use OpenSSL 3.x. 
However, upstream only provides static linking versions. Static linking also requires careful consideration of licensing (https://openssl-library.org/source/license/index.html).  
To avoid compilation issues, TLS is temporarily disabled (`notls`).
```
ld: warning: search path '/usr/local/opt/openssl@1.1/lib' not found
ld: warning: search path '/usr/local/opt/openssl/lib' not found
ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.3.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: …
```

fix: disable TLS for macOS until OpenSSL 3.x support

---

source/nijigenerate/viewport/package.d
source/nijigenerate/viewport/vertex/automesh/alpha_provider.d
source/nijigenerate/viewport/vertex/automesh/common.d
source/nijigenerate/viewport/vertex/automesh/contours.d
source/nijigenerate/viewport/vertex/automesh/grid.d
source/nijigenerate/viewport/vertex/automesh/optimum.d
source/nijigenerate/viewport/vertex/automesh/package.d
source/nijigenerate/viewport/vertex/automesh/skeletonize.d

Functional Summary
- Enable AutoMesh on non-Part targets (MeshGroup, Mask, Shape, arbitrary Node[]).
- Use CPU-readable alpha as the single source for contour/skeleton/optimum processing.
- Produce consistent results between Part and non-Part by mapping image-centered vertices into target-local space.
Implementation Overview
- Alpha input abstraction: introduce IAlphaProvider with concrete providers
- PartAlphaProvider, MeshGroupAlphaProvider, GenericProjectionAlphaProvider.
- Common helpers: AlphaInput utilities to acquire alpha (from Drawable or Provider) and map image-centered vertices to target-local coordinates.
- Processor unification: contours/grid/optimum/skeletonize share the same flow
- Step 1 (branch): acquire AlphaInput
- Step 2+: binarize alpha → process …

Add MeshGroup/Mask alpha input and mapping for AutoMesh

---

.github/workflows/build-and-candidate.yml
.github/workflows/build-and-release.yml
.github/workflows/nightly.yml
BUILD.md
dub.sdl

Resolve the missing x86_64 library issue by downloading from ghcr.io/v2/homebrew/core/openssl/3
refer to  https://github.com/Homebrew/homebrew-core/blob/main/Formula/o/openssl@3.rb
Nightly build dmg successfully
https://github.com/r888800009/nijigenerate/tree/fix/openssl_build
https://github.com/r888800009/nijigenerate/actions/runs/17530865249/job/49787639116

Fixed macos x86_64 OpenSSL linking

---

source/nijigenerate/api/mcp/http_transport.d
source/nijigenerate/api/mcp/https.d
source/nijigenerate/windows/settings.d

This PR introduces HTTPS support for MCP HttpTransport by generating a self-signed certificate programmatically.
The HTTPS server uses ECC P-256 for key generation.
The certificate and key are written to server.crt and server.key files for use with vibe.d.
This enhancement ensures that MCP authentication is not effectively bypassed due to unencrypted HTTP transport and provides a safer local testing environment.

[feature/mcp-auth] Add HTTPS support with self-signed certificate generation in HttpTransport

---

source/nijigenerate/api/mcp/auth.d
source/nijigenerate/commands/automesh/dynamic.d
source/nijigenerate/commands/package.d
source/nijigenerate/commands/viewport/palette.d
source/nijigenerate/viewport/vertex/automesh/optimum.d
source/nijigenerate/widgets/notification.d
source/nijigenerate/windows/settings.d

Summary
- Added per-processor AutoMesh commands with progress + Cancel
- Split Parts (background) vs Non-Parts (main-thread fiber) execution
- Implemented stacked NotificationPopup to avoid override of popped content by new notification.
- Fix: some bugs in optimum AutoMesh logic.

AutoMesh apply commands + stacked notifications

---

source/nijigenerate/core/actionstack.d
source/nijigenerate/core/window.d
source/nijigenerate/io/save.d
source/nijigenerate/project.d

Add savedIndex to action stack and expose incActionMarkSaved()/incActionIsModified()
- Update incIsProjectModified() to compare against last saved index
- Mark saved on manual saves; autosaves don’t change saved state
- Update window title to append ‘●’ when project has unsaved changes
- Refresh title on state changes each frame

feat(core): track saved state and show modified dot

---

source/nijigenerate/core/settings.d
source/nijigenerate/io/inimport.d
source/nijigenerate/windows/settings.d

LayerGroup in PSD/KRA is replaced with "DynamicComposite" in v0.9 release. This patch make it configurable in the setting window.

Make replacement Node configurable for LayerGroup in PSD/KRA file.

---

source/nijigenerate/api/mcp/server.d
source/nijigenerate/commands/model/set_deform_binding.d
source/nijigenerate/commands/package.d
source/nijigenerate/commands/vertex/define_mesh.d

- apply mesh from float[] verts + ushort[] inds
- SetDeformBinding: set binding values (deform or value) at keypoint 
- Auto-create bindings when missing (undoable)
- Type-driven (DeformationParameterBinding/ValueParameterBinding)
- Strict deform checks: even-length offsets, vertex-count match, deformable target
- No-ops on invalid/missing inputs; not runnable via shortcut
- Wire into commands package and AllCommandMaps

feat(commands): add DefineMeshCommand and SetDeformBindingComnand

---

source/nijigenerate/commands/puppet/view.d
source/nijigenerate/core/window.d
source/nijigenerate/panels/viewport.d
source/nijigenerate/viewport/base.d
source/nijigenerate/viewport/common/mesheditor/brushstate.d
source/nijigenerate/viewport/common/mesheditor/tools/brush.d
source/nijigenerate/widgets/mainmenu.d

Brush option has new "Teachrer" part option.
If you drop any `Part` object to that teacher part, brush started to use it as a "teacher" part.
Brush automatically fit the deformation to minimize the difference of current image and target "teacher" image.
If you prepare any texture image which can be the teacher of the deformation, you can semi-automatically adjust the deformation for the teacher image.

feature: Brush has new option to fit deformation to target teacher image automatically.
